export default {
  success: true,
  data: {
    memes: [
      {
        id: 1,
        url: "/images/Aint_no_body_got_time_fo_dat.jpg",
        name: "Aint_no_body_got_time_fo_dat.jpg",
      },
      { id: 2, url: "/images/BabyTroll.png", name: "BabyTroll.png" },
      { id: 3, url: "/images/Dat face.jpg", name: "Dat face.jpg" },
      { id: 4, url: "/images/GTFO.png", name: "GTFO.png" },
      { id: 5, url: "/images/Happy.png", name: "Happy.png" },
      { id: 6, url: "/images/Sniper.png", name: "Sniper.png" },
      { id: 7, url: "/images/Troll.png", name: "Troll.png" },
      { id: 8, url: "/images/YUNO.png", name: "YUNO.png" },
      {
        id: 9,
        url: "/images/accidentally_open_internet_explorer.jpg",
        name: "accidentally_open_internet_explorer.jpg",
      },
      { id: 10, url: "/images/advice_dog.jpg", name: "advice_dog.jpg" },
      {
        id: 11,
        url: "/images/advice_yoda_gives.jpg",
        name: "advice_yoda_gives.jpg",
      },
      {
        id: 12,
        url: "/images/aint_that_some_shit.jpg",
        name: "aint_that_some_shit.jpg",
      },
      { id: 13, url: "/images/alien.jpg", name: "alien.jpg" },
      {
        id: 14,
        url: "/images/angry_head_shake.jpg",
        name: "angry_head_shake.jpg",
      },
      { id: 15, url: "/images/anonymous_mask.jpg", name: "anonymous_mask.jpg" },
      {
        id: 16,
        url: "/images/anti_joke_chicken.jpg",
        name: "anti_joke_chicken.jpg",
      },
      {
        id: 17,
        url: "/images/are_you_fucking_kidding_me.jpg",
        name: "are_you_fucking_kidding_me.jpg",
      },
      { id: 18, url: "/images/arrow_in_knee.jpg", name: "arrow_in_knee.jpg" },
      { id: 19, url: "/images/aww_yeah.jpg", name: "aww_yeah.jpg" },
      { id: 20, url: "/images/black_facepalm.jpg", name: "black_facepalm.jpg" },
      { id: 21, url: "/images/black_rage2.jpg", name: "black_rage2.jpg" },
      {
        id: 22,
        url: "/images/blonde_fake_smile.jpg",
        name: "blonde_fake_smile.jpg",
      },
      {
        id: 23,
        url: "/images/blonde_fuck_that_bitch.jpg",
        name: "blonde_fuck_that_bitch.jpg",
      },
      { id: 24, url: "/images/brad_pitt.jpg", name: "brad_pitt.jpg" },
      { id: 25, url: "/images/broken_heart.jpg", name: "broken_heart.jpg" },
      { id: 26, url: "/images/brunette_gasp.jpg", name: "brunette_gasp.jpg" },
      {
        id: 27,
        url: "/images/challenge_accepted.jpg",
        name: "challenge_accepted.jpg",
      },
      {
        id: 28,
        url: "/images/challenge_denied.jpg",
        name: "challenge_denied.jpg",
      },
      {
        id: 29,
        url: "/images/concentrated_teeth.jpg",
        name: "concentrated_teeth.jpg",
      },
      {
        id: 30,
        url: "/images/conflicting_emotions.jpg",
        name: "conflicting_emotions.jpg",
      },
      { id: 31, url: "/images/courage_wolf.jpg", name: "courage_wolf.jpg" },
      {
        id: 32,
        url: "/images/everything_is_beatiful.jpg",
        name: "everything_is_beatiful.jpg",
      },
      { id: 33, url: "/images/facepalm.jpg", name: "facepalm.jpg" },
      {
        id: 34,
        url: "/images/female_aww_yeah.jpg",
        name: "female_aww_yeah.jpg",
      },
      {
        id: 35,
        url: "/images/fffffffuuuuuuuuuuuu.jpg",
        name: "fffffffuuuuuuuuuuuu.jpg",
      },
      {
        id: 36,
        url: "/images/first_world_problems.jpg",
        name: "first_world_problems.jpg",
      },
      {
        id: 37,
        url: "/images/fuck_yeah_smile.jpg",
        name: "fuck_yeah_smile.jpg",
      },
      { id: 38, url: "/images/fus_ro_dah.jpg", name: "fus_ro_dah.jpg" },
      { id: 39, url: "/images/grin.jpg", name: "grin.jpg" },
      { id: 40, url: "/images/grinch.jpg", name: "grinch.jpg" },
      { id: 41, url: "/images/red_ladystare.jpg", name: "red_ladystare.jpg" },
      { id: 42, url: "/images/so good.png", name: "so good.png" },
      {
        id: 43,
        url: "/images/so_close_freddie_mercury.jpg",
        name: "so_close_freddie_mercury.jpg",
      },
      { id: 44, url: "/images/troll_face.jpg", name: "troll_face.jpg" },
      { id: 45, url: "/images/troll_granny.jpg", name: "troll_granny.jpg" },
      {
        id: 46,
        url: "/images/tumblr_m4llyvFMvJ1r3zat8 - Copy.png",
        name: "tumblr_m4llyvFMvJ1r3zat8 - Copy.png",
      },
      { id: 47, url: "/images/wow.jpg", name: "wow.jpg" },
      { id: 48, url: "/images/wut.jpg", name: "wut.jpg" },
      { id: 49, url: "/images/y_u_no.jpg", name: "y_u_no.jpg" },
      {
        id: 50,
        url: "/images/yes_this_is_dog.jpg",
        name: "yes_this_is_dog.jpg",
      },
      { id: 51, url: "/images/yesterday.jpg", name: "yesterday.jpg" },
      { id: 52, url: "/images/yo_dawg.jpg", name: "yo_dawg.jpg" },
      { id: 53, url: "/images/you_dont_say.jpg", name: "you_dont_say.jpg" },
      { id: 54, url: "/images/youre_the_man.jpg", name: "youre_the_man.jpg" },
    ],
  },
};
